### ISSUE TITLE
Tracebacks trying to run  in Maya 2024.1 on macOS

### ISSUE THREAD

**Issue by RJJ** [sol-ansano-kim/medic#14]
Getting the Tracebacks below trying to run  in Maya 2024.1 on macOS 14 (Apple Silicon) 

Using these files: [medic_macOS_maya2024-1_5_4.zip](https://github.com/sol-ansano-kim/medic/releases/download/1.5.4/medic_macOS_maya2024-1_5_4.zip)

note: also tried in Maya 2024.1 on macOS 14 (Intel) and getting the same errors about no such file.

Error below when running on macOS 14 (Apple Silicon):
import medicUI
medicUI.Show()
# Error: dlopen(/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/_medic.so, 0x0002): tried: '/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/_medic.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/_medic.so' (no such file), '/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/_medic.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
# # Traceback (most recent call last):
# #   File "<maya console>", line 1, in <module>
# #   File "/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/medicUI/__init__.py", line 1, in <module>
# #     from . import window
# #   File "/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/medicUI/window.py", line 2, in <module>
# #     from . import widgets
# #   File "/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/medicUI/widgets.py", line 2, in <module>
# #     from . import model
# #   File "/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/medicUI/model.py", line 1, in <module>
# #     import medic
# #   File "/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/medic.py", line 11, in <module>
# #     from _medic import *
# # ImportError: dlopen(/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/_medic.so, 0x0002): tried: '/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/_medic.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/_medic.so' (no such file), '/Users/rjj/Library/Preferences/Autodesk/maya/2024/modules/medic/py/_medic.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

**Comment by sol-ansano-kim** [comment]
Oops, I haven't built for 2024...
